import { db } from '@/db';
import { reviewsTable } from '@/db/schema';

async function main() {
    const sampleReviews = [
        // 5-STAR REVIEWS (8 reviews - 45%)
        {
            serviceId: 3,
            reviewerId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            reviewerName: 'Grace Wanjiku',
            rating: 5,
            title: 'Exceptional plumbing service! Very professional',
            comment: 'This plumber arrived on time and fixed my burst pipe in Westlands perfectly. Clean work, fair price, and explained everything. Highly recommend! Will call again.',
            helpfulCount: 12,
            verifiedPurchase: true,
            providerResponse: 'Thank you for the kind words! Customer satisfaction is our priority. Looking forward to serving you again.',
            responseDate: new Date('2024-11-18').toISOString(),
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            serviceId: 8,
            reviewerId: 'user_02h5lyt3f9a1z4c2o8n7r6x9s5',
            reviewerName: 'Amina Hassan',
            rating: 5,
            title: 'Best braids in Nairobi!',
            comment: 'Safi sana! My box braids turned out perfect. The lady was gentle, used quality extensions, and the salon was clean. Worth every shilling. Already booked my next appointment.',
            helpfulCount: 15,
            verifiedPurchase: true,
            providerResponse: 'Asante for choosing us! We are glad you loved your braids. See you soon!',
            responseDate: new Date('2024-10-24').toISOString(),
            createdAt: new Date('2024-10-22').toISOString(),
            updatedAt: new Date('2024-10-22').toISOString(),
        },
        {
            serviceId: 12,
            reviewerId: 'user_03h6mzu4g0b2a5d3p9o8s7y0t6',
            reviewerName: 'David Kamau',
            rating: 5,
            title: 'Perfect catering for our wedding',
            comment: 'The food was amazing! They catered our church wedding in Karen with 200 guests. Everything was fresh, hot, and delicious. Very organized team. Highly professional!',
            helpfulCount: 14,
            verifiedPurchase: true,
            providerResponse: 'Congratulations on your wedding! It was our pleasure to be part of your special day. Wishing you both a blessed marriage!',
            responseDate: new Date('2024-09-07').toISOString(),
            createdAt: new Date('2024-09-05').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },
        {
            serviceId: 5,
            reviewerId: 'user_04h7nav5h1c3b6e4q0p9t8z1u7',
            reviewerName: 'Mary Akinyi',
            rating: 5,
            title: 'Outstanding house cleaning',
            comment: 'Poa sana! They cleaned my 3-bedroom house in Kasarani thoroughly. Even cleaned the windows and organized the kitchen. Very trustworthy team. Will book monthly.',
            helpfulCount: 11,
            verifiedPurchase: true,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            serviceId: 15,
            reviewerId: 'user_05h8obw6i2d4c7f5r1q0u9a2v8',
            reviewerName: 'James Otieno',
            rating: 5,
            title: 'Fast and reliable transport',
            comment: 'Driver was punctual and professional. Clean car, smooth ride from Eastleigh to town. Fair price and even helped with my luggage. Will use again for sure!',
            helpfulCount: 9,
            verifiedPurchase: true,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            serviceId: 6,
            reviewerId: 'user_06h9pcx7j3e5d8g6s2r1v0b3w9',
            reviewerName: 'Lucy Muthoni',
            rating: 5,
            title: 'Excellent electrical work',
            comment: 'Fixed all my wiring issues in one visit. Very knowledgeable electrician who explained everything clearly. Fair pricing and left the place clean. Highly recommend!',
            helpfulCount: 10,
            verifiedPurchase: true,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-10-10').toISOString(),
            updatedAt: new Date('2024-10-10').toISOString(),
        },
        {
            serviceId: 17,
            reviewerId: 'user_07h0qdy8k4f6e9h7t3s2w1c4x0',
            reviewerName: 'Peter Omondi',
            rating: 5,
            title: 'Top-notch carpentry skills',
            comment: 'Made beautiful custom cabinets for my kitchen. Quality wood, perfect finishing, and installed everything professionally. Worth every shilling paid. Asante sana!',
            helpfulCount: 13,
            verifiedPurchase: true,
            providerResponse: 'Thank you Peter! Glad you are happy with your new cabinets. Feel free to call us for any future projects.',
            responseDate: new Date('2024-08-15').toISOString(),
            createdAt: new Date('2024-08-12').toISOString(),
            updatedAt: new Date('2024-08-12').toISOString(),
        },
        {
            serviceId: 10,
            reviewerId: 'user_08h1rez9l5g7f0i8u4t3x2d5y1',
            reviewerName: 'Sarah Njeri',
            rating: 5,
            title: 'Amazing massage therapy',
            comment: 'Best massage I have had in Nairobi! Very professional therapist who understood my back pain issues. Felt so relaxed after. Already booked my next session.',
            helpfulCount: 8,
            verifiedPurchase: true,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
        },
        // 4-STAR REVIEWS (6 reviews - 33%)
        {
            serviceId: 4,
            reviewerId: 'user_09h2sfa0m6h8g1j9v5u4y3e6z2',
            reviewerName: 'Michael Kipchoge',
            rating: 4,
            title: 'Good work but took longer than expected',
            comment: 'The electrician did quality wiring for my house in Karen. Everything works well but took 2 extra days to finish. Good communication though. Would hire again.',
            helpfulCount: 7,
            verifiedPurchase: true,
            providerResponse: 'Pole for the delay. We had to source special materials but ensured quality. Thank you for understanding!',
            responseDate: new Date('2024-09-28').toISOString(),
            createdAt: new Date('2024-09-25').toISOString(),
            updatedAt: new Date('2024-09-25').toISOString(),
        },
        {
            serviceId: 7,
            reviewerId: 'user_10h3tgb1n7i9h2k0w6v5z4f7a3',
            reviewerName: 'Elizabeth Wairimu',
            rating: 4,
            title: 'Decent cleaning service',
            comment: 'House cleaning was thorough but they arrived 1 hour late. Once they started, work was professional. Used good products. Fair pricing for Nairobi standards.',
            helpfulCount: 5,
            verifiedPurchase: true,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            serviceId: 13,
            reviewerId: 'user_11h4uhc2o8j0i3l1x7w6a5g8b4',
            reviewerName: 'Robert Mwangi',
            rating: 4,
            title: 'Good food delivery',
            comment: 'Food quality is excellent and portions are generous. Delivery took a bit longer than promised but the rider was polite. M-Pesa payment was smooth. Will order again.',
            helpfulCount: 6,
            verifiedPurchase: true,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            serviceId: 9,
            reviewerId: 'user_12h5vid3p9k1j4m2y8x7b6h9c5',
            reviewerName: 'Nancy Chebet',
            rating: 4,
            title: 'Professional makeup artist',
            comment: 'She did great makeup for my sister harambee. Looked natural and lasted the whole day. Slightly expensive but quality work. Would recommend for special occasions.',
            helpfulCount: 4,
            verifiedPurchase: false,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            serviceId: 14,
            reviewerId: 'user_13h6wje4q0l2k5n3z9y8c7i0d6',
            reviewerName: 'Joseph Mutua',
            rating: 4,
            title: 'Reliable car wash',
            comment: 'They cleaned my car well and the interior detailing was good. Took a bit longer than expected but thorough work. Location in Westlands is convenient. Fair price.',
            helpfulCount: 5,
            verifiedPurchase: true,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            serviceId: 2,
            reviewerId: 'user_14h7xkf5r1m3l6o4a0z9d8j1e7',
            reviewerName: 'Catherine Njoki',
            rating: 4,
            title: 'Good plumbing repair',
            comment: 'Fixed my leaking sink quickly. Plumber was skilled and friendly. Only issue was he did not have all tools so had to go buy some. Otherwise good service.',
            helpfulCount: 3,
            verifiedPurchase: true,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2024-08-20').toISOString(),
        },
        // 3-STAR REVIEWS (2 reviews - 11%)
        {
            serviceId: 11,
            reviewerId: 'user_15h8ylg6s2n4m7p5b1a0e9k2f8',
            reviewerName: 'Daniel Odhiambo',
            rating: 3,
            title: 'Okay but communication needs improvement',
            comment: 'The service was done but had to call multiple times to confirm timing. Work quality is average. Not bad but expected better for the price charged.',
            helpfulCount: 2,
            verifiedPurchase: false,
            providerResponse: null,
            responseDate: null,
            createdAt: new Date('2024-10-30').toISOString(),
            updatedAt: new Date('2024-10-30').toISOString(),
        },
        {
            serviceId: 16,
            reviewerId: 'user_16h9zmh7t3o5n8q6c2b1f0l3g9',
            reviewerName: 'Jane Waithera',
            rating: 3,
            title: 'Mixed experience with food delivery',
            comment: 'Chapatis were good but delivery took too long. When they arrived, food was warm not hot. Taste was fine. Would order again only if they improve delivery time.',
            helpfulCount: 3,
            verifiedPurchase: true,
            providerResponse: 'Pole sana for the delay. We are working on improving our delivery times. Thank you for the feedback.',
            responseDate: new Date('2024-12-08').toISOString(),
            createdAt: new Date('2024-12-06').toISOString(),
            updatedAt: new Date('2024-12-06').toISOString(),
        },
        // 2-STAR REVIEW (1 review - 6%)
        {
            serviceId: 1,
            reviewerId: 'user_17h0ani8u4p6o9r7d3c2g1m4h0',
            reviewerName: 'Patrick Kimani',
            rating: 2,
            title: 'Disappointed with the service',
            comment: 'Plumber came late without calling. Work was rushed and I found a small leak again after 3 days. Had to call another person to redo it. Not professional.',
            helpfulCount: 4,
            verifiedPurchase: true,
            providerResponse: 'Pole sana for the poor experience. This is not our standard. Please call me directly to make this right. Will fix at no charge.',
            responseDate: new Date('2024-07-18').toISOString(),
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-07-15').toISOString(),
        },
        // 1-STAR REVIEW (1 review - 6%)
        {
            serviceId: 18,
            reviewerId: 'user_18h1boj9v5q7p0s8e4d3h2n5i1',
            reviewerName: 'Susan Auma',
            rating: 1,
            title: 'Terrible experience, avoid!',
            comment: 'Very unprofessional. Carpenter arrived 2 hours late, made my cabinet wonky, and became rude when I complained. Had to hire someone else to fix his mistakes. Waste of money!',
            helpfulCount: 8,
            verifiedPurchase: true,
            providerResponse: 'We sincerely apologize. This is unacceptable behavior. Please contact us immediately so we can rectify this and provide a full refund.',
            responseDate: new Date('2024-09-02').toISOString(),
            createdAt: new Date('2024-08-30').toISOString(),
            updatedAt: new Date('2024-08-30').toISOString(),
        },
    ];

    await db.insert(reviewsTable).values(sampleReviews);
    
    console.log('✅ Reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});