import { db } from '@/db';
import { serviceRequests } from '@/db/schema';
import { sql } from 'drizzle-orm';

async function main() {
    // Delete all existing records first
    await db.run(sql`DELETE FROM service_requests`);
    console.log('🗑️ Cleared existing service_requests');

    const sampleServiceRequests = [
        // OPEN REQUESTS (35 records - 70%)
        // Last 1 hour (7 requests)
        {
            customerName: 'Peter Mwangi',
            customerPhone: '+254712345678',
            customerLocation: 'Westlands',
            serviceCategory: 'cleaning',
            description: 'Nataka someone wa ku-clean my 2-bedroom apartment kesho. Must be thorough.',
            budget: 3500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T14:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Grace Wanjiku',
            customerPhone: '+254722456789',
            customerLocation: 'Kilimani',
            serviceCategory: 'plumbing',
            description: 'Pipe burst in kitchen! Emergency plumber needed ASAP. Maji inapotea sana.',
            budget: 5000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T14:45:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'David Omondi',
            customerPhone: '+254733567890',
            customerLocation: 'Karen',
            serviceCategory: 'salon',
            description: 'Need box braids for wedding this Saturday. Must be neat and professional.',
            budget: 3800,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T15:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Mary Akinyi',
            customerPhone: '+254744678901',
            customerLocation: 'Lavington',
            serviceCategory: 'repairs',
            description: 'My fridge imeharibika. Need urgent repair services. Saa ngapi mnafika?',
            budget: 4500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T15:10:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'James Njoroge',
            customerPhone: '+254755789012',
            customerLocation: 'Eastleigh',
            serviceCategory: 'electrical',
            description: 'Power sockets not working in 3 rooms. Need electrician. Must be licensed.',
            budget: 6500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T15:15:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Faith Njeri',
            customerPhone: '+254766890123',
            customerLocation: 'Parklands',
            serviceCategory: 'carpentry',
            description: 'Looking for fundi to make custom kitchen cabinets. Quality wood required.',
            budget: 18000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T15:20:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Joseph Otieno',
            customerPhone: '+254777901234',
            customerLocation: 'Kasarani',
            serviceCategory: 'painting',
            description: '4 bedroom house needs repainting. Interior and exterior. Serious painters only.',
            budget: 35000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T15:25:00.000Z',
            matchedAt: null,
        },

        // Last 6 hours (11 requests)
        {
            customerName: 'Catherine Chebet',
            customerPhone: '+254788012345',
            customerLocation: 'Embakasi',
            serviceCategory: 'photography',
            description: 'Need photographer for ruracio ceremony next month. Experience with traditional events.',
            budget: 12000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T09:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Samuel Kipchoge',
            customerPhone: '+254799123456',
            customerLocation: 'Donholm',
            serviceCategory: 'catering',
            description: 'Catering for office party, 50 people. Chicken, rice, chapati. Delivery Friday.',
            budget: 25000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T10:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Lucy Muthoni',
            customerPhone: '+254710234567',
            customerLocation: 'Ruaka',
            serviceCategory: 'transport',
            description: 'Regular boda boda guy needed for daily CBD deliveries. Must be reliable.',
            budget: 5000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T10:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Daniel Wanyama',
            customerPhone: '+254721345678',
            customerLocation: 'South B',
            serviceCategory: 'tutoring',
            description: 'Math tutor needed for Form 3 student. Weekends only. Budget 2k per session.',
            budget: 2000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T11:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Jane Waithera',
            customerPhone: '+254732456789',
            customerLocation: 'South C',
            serviceCategory: 'it_support',
            description: 'Laptop ime-hang constantly. Need IT guy to check virus or hardware.',
            budget: 3500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T11:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Patrick Mutua',
            customerPhone: '+254743567890',
            customerLocation: 'Runda',
            serviceCategory: 'tailoring',
            description: 'Need suit alterations urgently for interview. Budget around 1500.',
            budget: 1500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T12:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Anne Adhiambo',
            customerPhone: '+254754678901',
            customerLocation: 'Kileleshwa',
            serviceCategory: 'events',
            description: 'Planning engagement party, need event planning. Venue, decor, PA system.',
            budget: 85000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T12:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Brian Kimani',
            customerPhone: '+254765789012',
            customerLocation: 'Langata',
            serviceCategory: 'landscaping',
            description: 'Compound overgrown. Need gardening including trimming and planting.',
            budget: 12000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T13:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Susan Jepkoech',
            customerPhone: '+254776890123',
            customerLocation: 'Roysambu',
            serviceCategory: 'food',
            description: 'Daily lunch deliveries for office of 15 staff. Healthy meals.',
            budget: 9000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T13:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Michael Odhiambo',
            customerPhone: '+254787901234',
            customerLocation: 'Zimmerman',
            serviceCategory: 'cleaning',
            description: 'Deep cleaning for 3 bedroom house. Carpet shampooing included.',
            budget: 4500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T14:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Esther Wangari',
            customerPhone: '+254798012345',
            customerLocation: 'Ngong',
            serviceCategory: 'repairs',
            description: 'Washing machine not spinning. Need technician to fix or advise.',
            budget: 3000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T14:15:00.000Z',
            matchedAt: null,
        },

        // Last 24 hours (11 requests)
        {
            customerName: 'Charles Kariuki',
            customerPhone: '+254709123456',
            customerLocation: 'Kitisuru',
            serviceCategory: 'salon',
            description: 'Bridal makeup na hair styling for Saturday wedding. Portfolio is a must.',
            budget: 4000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-12T15:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Rose Nafula',
            customerPhone: '+254720234567',
            customerLocation: 'Thika Road',
            serviceCategory: 'plumbing',
            description: 'Bathroom drainage blocked. Water backing up everywhere. Help needed.',
            budget: 4500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-12T18:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Dennis Wekesa',
            customerPhone: '+254731345678',
            customerLocation: 'CBD',
            serviceCategory: 'electrical',
            description: 'Office power installation for 10 computers. Need professional wiring.',
            budget: 25000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-12T20:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Betty Nyambura',
            customerPhone: '+254742456789',
            customerLocation: 'Pipeline',
            serviceCategory: 'carpentry',
            description: 'Wardrobe repair - door hanging loose. Also need new shelves fitted.',
            budget: 6500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-12T22:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Paul Koech',
            customerPhone: '+254753567890',
            customerLocation: 'Umoja',
            serviceCategory: 'painting',
            description: 'Repainting rental bedsitter. Looking for quick quality job.',
            budget: 8500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T01:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Agnes Moraa',
            customerPhone: '+254764678901',
            customerLocation: 'Buruburu',
            serviceCategory: 'photography',
            description: 'Product photography for online shop. Need clean professional shots.',
            budget: 6000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T03:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'George Nyambane',
            customerPhone: '+254775789012',
            customerLocation: 'Kawangware',
            serviceCategory: 'catering',
            description: 'Birthday party for 30 kids. Need snacks, cake, drinks. This Sunday.',
            budget: 15000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T05:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Nancy Awino',
            customerPhone: '+254786890123',
            customerLocation: 'Kibera',
            serviceCategory: 'transport',
            description: 'Need pickup truck for house moving from Kibera to Rongai this weekend.',
            budget: 6000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T06:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Steven Makori',
            customerPhone: '+254797901234',
            customerLocation: 'Githurai',
            serviceCategory: 'tutoring',
            description: 'English and Kiswahili tutor for Class 7. KCPE prep starting immediately.',
            budget: 3500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T07:30:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Caroline Chepkemoi',
            customerPhone: '+254708012345',
            customerLocation: 'Kahawa West',
            serviceCategory: 'it_support',
            description: 'WiFi setup and network configuration for small office. 5 workstations.',
            budget: 7000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T08:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Francis Wafula',
            customerPhone: '+254719123456',
            customerLocation: 'Dagoretti',
            serviceCategory: 'tailoring',
            description: 'Custom made kitenge dress for church event. Have material already.',
            budget: 3500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-13T09:00:00.000Z',
            matchedAt: null,
        },

        // 2-7 days ago (6 requests)
        {
            customerName: 'Margaret Wambui',
            customerPhone: '+254730234567',
            customerLocation: 'Kayole',
            serviceCategory: 'events',
            description: 'DJ and MC needed for corporate team building next Friday. Must have own equipment.',
            budget: 30000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-06T10:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Timothy Maina',
            customerPhone: '+254741345678',
            customerLocation: 'Kangemi',
            serviceCategory: 'landscaping',
            description: 'Front yard redesign with grass, flowers and pathway. Professional landscaper needed.',
            budget: 22000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-07T14:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Rebecca Atieno',
            customerPhone: '+254752456789',
            customerLocation: 'Mombasa',
            serviceCategory: 'food',
            description: 'Weekly meal prep service. 5 days, lunch and dinner. Swahili dishes preferred.',
            budget: 8000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-08T11:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Robert Kiplagat',
            customerPhone: '+254763567890',
            customerLocation: 'Kisumu',
            serviceCategory: 'cleaning',
            description: 'Office cleaning services. 3 times a week. Must be trustworthy.',
            budget: 2500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-09T09:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Elizabeth Jeptoo',
            customerPhone: '+254774678901',
            customerLocation: 'Nakuru',
            serviceCategory: 'repairs',
            description: 'TV screen cracked. Need assessment if repairable or replacement needed.',
            budget: 5000,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-10T13:00:00.000Z',
            matchedAt: null,
        },
        {
            customerName: 'Anthony Njeri',
            customerPhone: '+254785789012',
            customerLocation: 'Eldoret',
            serviceCategory: 'salon',
            description: 'Dreadlocks maintenance and retwist. Been 2 months since last session.',
            budget: 2500,
            status: 'open',
            matchedProviderId: null,
            createdAt: '2025-01-11T15:00:00.000Z',
            matchedAt: null,
        },

        // MATCHED REQUESTS (10 records - 20%)
        {
            customerName: 'Ruth Kerubo',
            customerPhone: '+254796890123',
            customerLocation: 'Thika',
            serviceCategory: 'plumbing',
            description: 'Water heater not heating. Need someone to check and repair ASAP.',
            budget: 6000,
            status: 'matched',
            matchedProviderId: 'test_provider_001',
            createdAt: '2025-01-12T10:00:00.000Z',
            matchedAt: '2025-01-12T11:30:00.000Z',
        },
        {
            customerName: 'Vincent Ouma',
            customerPhone: '+254707901234',
            customerLocation: 'Kiambu',
            serviceCategory: 'electrical',
            description: 'Need KPLC approved electrician for new meter installation and wiring.',
            budget: 38000,
            status: 'matched',
            matchedProviderId: 'test_provider_002',
            createdAt: '2025-01-11T14:00:00.000Z',
            matchedAt: '2025-01-11T16:45:00.000Z',
        },
        {
            customerName: 'Joyce Mumbi',
            customerPhone: '+254718012345',
            customerLocation: 'Machakos',
            serviceCategory: 'carpentry',
            description: 'Building new chicken coop. Need carpenter for framing and roofing.',
            budget: 15000,
            status: 'matched',
            matchedProviderId: 'test_provider_003',
            createdAt: '2025-01-10T08:00:00.000Z',
            matchedAt: '2025-01-10T09:15:00.000Z',
        },
        {
            customerName: 'Sarah Wairimu',
            customerPhone: '+254729123456',
            customerLocation: 'Nyeri',
            serviceCategory: 'painting',
            description: 'New house needs complete interior painting. 5 bedrooms, living, dining.',
            budget: 42000,
            status: 'matched',
            matchedProviderId: 'test_provider_001',
            createdAt: '2025-01-09T12:00:00.000Z',
            matchedAt: '2025-01-09T14:20:00.000Z',
        },
        {
            customerName: 'Peter Kimutai',
            customerPhone: '+254740234567',
            customerLocation: 'Naivasha',
            serviceCategory: 'photography',
            description: 'Family photoshoot at Lake Naivasha. Need photographer with experience in outdoor shoots.',
            budget: 8500,
            status: 'matched',
            matchedProviderId: 'test_provider_002',
            createdAt: '2025-01-08T15:00:00.000Z',
            matchedAt: '2025-01-08T17:35:00.000Z',
        },
        {
            customerName: 'John Kamau',
            customerPhone: '+254751345678',
            customerLocation: 'Ruiru',
            serviceCategory: 'catering',
            description: 'Need lunch catering for construction site. 20 workers daily for 2 weeks.',
            budget: 35000,
            status: 'matched',
            matchedProviderId: 'test_provider_003',
            createdAt: '2025-01-07T09:00:00.000Z',
            matchedAt: '2025-01-07T10:50:00.000Z',
        },
        {
            customerName: 'Grace Cherop',
            customerPhone: '+254762456789',
            customerLocation: 'Juja',
            serviceCategory: 'transport',
            description: 'School run needed. Pick and drop kids from Juja to Ruiru. Weekdays only.',
            budget: 7500,
            status: 'matched',
            matchedProviderId: 'test_provider_001',
            createdAt: '2025-01-06T16:00:00.000Z',
            matchedAt: '2025-01-06T18:15:00.000Z',
        },
        {
            customerName: 'David Kiprop',
            customerPhone: '+254773567890',
            customerLocation: 'Rongai',
            serviceCategory: 'tutoring',
            description: 'Chemistry and Biology tutor for Form 4. Intensive KCSE preparation needed.',
            budget: 4200,
            status: 'matched',
            matchedProviderId: 'test_provider_002',
            createdAt: '2025-01-12T08:00:00.000Z',
            matchedAt: '2025-01-12T10:25:00.000Z',
        },
        {
            customerName: 'Mary Wanjiru',
            customerPhone: '+254784678901',
            customerLocation: 'Kikuyu',
            serviceCategory: 'it_support',
            description: 'Computer very slow. Need virus removal and system optimization.',
            budget: 3000,
            status: 'matched',
            matchedProviderId: 'test_provider_003',
            createdAt: '2025-01-11T11:00:00.000Z',
            matchedAt: '2025-01-11T12:45:00.000Z',
        },
        {
            customerName: 'James Otieno',
            customerPhone: '+254795789012',
            customerLocation: 'Limuru',
            serviceCategory: 'tailoring',
            description: 'School uniforms for 3 kids. Have measurements and material ready.',
            budget: 4500,
            status: 'matched',
            matchedProviderId: 'test_provider_001',
            createdAt: '2025-01-10T10:00:00.000Z',
            matchedAt: '2025-01-10T11:40:00.000Z',
        },

        // COMPLETED REQUESTS (5 records - 10%)
        {
            customerName: 'Faith Achieng',
            customerPhone: '+254706890123',
            customerLocation: 'Tigoni',
            serviceCategory: 'events',
            description: 'Wedding planning full package. Venue, decor, catering, entertainment.',
            budget: 125000,
            status: 'completed',
            matchedProviderId: 'test_provider_002',
            createdAt: '2025-01-05T09:00:00.000Z',
            matchedAt: '2025-01-05T09:35:00.000Z',
        },
        {
            customerName: 'Joseph Kemboi',
            customerPhone: '+254717901234',
            customerLocation: 'Muthaiga',
            serviceCategory: 'landscaping',
            description: 'Complete garden makeover including irrigation system installation.',
            budget: 24000,
            status: 'completed',
            matchedProviderId: 'test_provider_003',
            createdAt: '2025-01-04T11:00:00.000Z',
            matchedAt: '2025-01-04T11:28:00.000Z',
        },
        {
            customerName: 'Catherine Wambui',
            customerPhone: '+254728012345',
            customerLocation: 'Spring Valley',
            serviceCategory: 'food',
            description: 'Private chef for dinner party. 8 guests. 3-course meal required.',
            budget: 11000,
            status: 'completed',
            matchedProviderId: 'test_provider_001',
            createdAt: '2025-01-03T14:00:00.000Z',
            matchedAt: '2025-01-03T14:22:00.000Z',
        },
        {
            customerName: 'Samuel Maina',
            customerPhone: '+254739123456',
            customerLocation: 'Ridgeways',
            serviceCategory: 'cleaning',
            description: 'Post-construction cleaning. New house needs thorough cleaning before moving in.',
            budget: 4200,
            status: 'completed',
            matchedProviderId: 'test_provider_002',
            createdAt: '2025-01-02T10:00:00.000Z',
            matchedAt: '2025-01-02T10:18:00.000Z',
        },
        {
            customerName: 'Lucy Njoki',
            customerPhone: '+254750234567',
            customerLocation: 'Kileleshwa',
            serviceCategory: 'repairs',
            description: 'AC not cooling properly. Need servicing and gas refill if necessary.',
            budget: 5500,
            status: 'completed',
            matchedProviderId: 'test_provider_003',
            createdAt: '2025-01-01T13:00:00.000Z',
            matchedAt: '2025-01-01T13:42:00.000Z',
        },
    ];

    await db.insert(serviceRequests).values(sampleServiceRequests);
    
    console.log('✅ Service requests seeder completed successfully - 50 records inserted');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});