import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const sampleTransactions = [
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 1,
            mpesaCode: 'RBK7M3N8P2',
            amount: 1500,
            transactionType: 'payment',
            description: 'Laundry service for 3 items',
            transactionDate: new Date('2024-12-15T10:30:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 2,
            mpesaCode: 'RBK9A4C6D8',
            amount: 3500,
            transactionType: 'payment',
            description: 'Full house cleaning',
            transactionDate: new Date('2024-12-18T14:20:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: null,
            mpesaCode: null,
            amount: 800,
            transactionType: 'expense',
            description: 'Bought cleaning supplies',
            transactionDate: new Date('2024-12-20T09:15:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 3,
            mpesaCode: 'RBK2H5J7K9',
            amount: 5000,
            transactionType: 'payment',
            description: 'Electrical wiring repair',
            transactionDate: new Date('2024-12-22T11:45:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 4,
            mpesaCode: 'RBK6P8Q3R1',
            amount: 2500,
            transactionType: 'payment',
            description: 'Hair braiding - box braids',
            transactionDate: new Date('2024-12-23T16:00:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: null,
            mpesaCode: null,
            amount: 300,
            transactionType: 'expense',
            description: 'Transport fare',
            transactionDate: new Date('2024-12-24T08:30:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 5,
            mpesaCode: 'RBK3S9T4U7',
            amount: 1200,
            transactionType: 'payment',
            description: 'Laundry service for 5 items',
            transactionDate: new Date('2024-12-26T13:25:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 6,
            mpesaCode: 'RBK8V2W5X6',
            amount: 4500,
            transactionType: 'payment',
            description: 'Plumbing installation work',
            transactionDate: new Date('2024-12-28T10:15:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: null,
            mpesaCode: null,
            amount: 2000,
            transactionType: 'expense',
            description: 'Purchased electrical tools',
            transactionDate: new Date('2024-12-29T15:40:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 7,
            mpesaCode: 'RBK1Y7Z8A3',
            amount: 800,
            transactionType: 'payment',
            description: 'Window cleaning service',
            transactionDate: new Date('2024-12-30T09:50:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 8,
            mpesaCode: 'RBK4B9C2D5',
            amount: 3000,
            transactionType: 'payment',
            description: 'Carpet cleaning - 3 rooms',
            transactionDate: new Date('2025-01-02T12:30:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: null,
            mpesaCode: null,
            amount: 8000,
            transactionType: 'expense',
            description: 'Rent payment',
            transactionDate: new Date('2025-01-05T08:00:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: null,
            mpesaCode: 'RBK7E3F6G8',
            amount: 500,
            transactionType: 'payment',
            description: 'Ironing service - 10 pieces',
            transactionDate: new Date('2025-01-07T14:20:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: 9,
            mpesaCode: 'RBK5H8J1K4',
            amount: 2000,
            transactionType: 'payment',
            description: 'Sofa cleaning service',
            transactionDate: new Date('2025-01-09T11:10:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            customerId: null,
            mpesaCode: null,
            amount: 450,
            transactionType: 'expense',
            description: 'Water bill',
            transactionDate: new Date('2025-01-10T16:45:00').toISOString(),
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});